### ISSUE TITLE
TODO: improve docs for ICEBERG

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/wv2-processing#30]
examples:
* https://github.com/iceberg-project/Seals
* https://github.com/iceberg-project/Penguins

TODO
* [x] post (private) testdata on gdrive
* [x] clean & update docs for this repo
* [x] clean & update docs for 7yl4r/imagery-utils
* [X] create [gist](https://gist.github.com/7yl4r/3850886b88645bd465b4b72ef07660f1) outlining how to use the two together

To complete these I am going to need to test installing on a new system.
